version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "mongodb/config:/etc/mongo"
      - "mongodb/data/db:/data/db"
      - "mongodb/data/configdb:/data/configdb"
    networks:
      - backend
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
volumes:
  mongodb:
    driver: local
networks:
  backend: